version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: youx
      POSTGRES_USER: youx
      POSTGRES_PASSWORD: youx
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "--username", "youx" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s

# Na pasta devops, execute esses comandos no terminal:
# docker-compose up -d
# docker-compose down
# docker-compose rm

#Acessando o container e verificando as tabelas ou pode ser feito por ferramentas como datagrip, dbeaver e outras.
#docker exec -it postgres psql -U youx youx
#\dt

#Verificando o estado do postgresql
#docker inspect --format='{{json .State.Health}}' postgres